### ISSUE TITLE
RuntimeError on Rails v5.0.0.beta1 when following instructions from README.md

### ISSUE THREAD

**Issue by janraasch** [rails/actionpack-xml_parser#13]
Hi there, Happy New Year! :-)

Having

```ruby
config.middleware.insert_after ActionDispatch::ParamsParser, ActionDispatch::XmlParamsParser
```

in `config/application.rb` yields

```bash
actionpack-5.0.0.beta1/lib/action_dispatch/middleware/stack.rb:99:in `assert_index': No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError)
```

when running on `rails v5.0.0.beta1`. This is due to https://github.com/rails/rails/commit/a1ced8b52ce60d0634e65aa36cb89f015f9f543d.

What is/will be the preferred way of using this gem in apps running on `rails v5`?

**Comment by li-qiang** [comment]
+1

**Comment by gkop** [comment]
If you bundle this gem from GitHub (the RubyGems release is not current), than might work for you (it's working for me with v5.0.0.beta4):

```ruby
config.middleware.use ActionDispatch::XmlParamsParser
```

**Comment by rafaelfranca** [comment]
This should be fixed on master. You shouldn't need to do anything other than add the gem to Gemfile
