### ISSUE TITLE
Register encoder

### ISSUE THREAD

**Issue by courtenay** [rails/actionpack-xml_parser#16]
In rails 4/5 integration tests, you can do something like

    get foo_path, 
      params: {...}, 
      as: :json

there's only one inbuilt option to the `as:` param, `:json` - to get xml working in a similar you have to register the encoder something like this:

    ActionDispatch::IntegrationTest.register_encoder :xml,
      param_encoder: -> params { params.to_xml },
      response_parser: -> body { body }

I'd say that xml_parser plugin should do this for you..?

**Comment by kaspth** [comment]
`:as` was added in Rails 5.

You'd need to wrap it in an `on_load` hook for the integration tests and a `respond_to?(:register_encoder)` as well.

The response parser probably needs more help than just return the xml string. Given this library has an XML parser we should be able to parse the contents.

Looking forward to your PR!
