### ISSUE TITLE
Parse errors potentially result in sensitive information being logged

### ISSUE THREAD

**Issue by ghost** [rails/actionpack-xml_parser#17]
When an XML parsing error occurs, raw XML is logged with the error

```
ActionDispatch::ParamsParser::ParseError (#<RuntimeError: Illegal character '&' in raw string
```

This raw XML output bypasses any parameter filtering.

**Comment by rafaelfranca** [comment]
This gem doesn't log anything. What is being logged is the exception by rails. Some exceptions may contain sensitive information, indeed. So it would probably be better to avoid the message on Rails. Anyway, this exception should be better of in the rails repository.
