### ISSUE TITLE
Instructions on enabling?

### ISSUE THREAD

**Issue by danwhitston** [rails/actionpack-xml_parser#18]
Previous versions of the gem had instructions on enabling XML parsing, namely adding `config.middleware.insert_after ActionDispatch::ParamsParser, ActionDispatch::XmlParamsParser` after `ActionDispatch::ParamsParser` in config/application.rb and possibly `require 'action_dispatch/xml_params_parser'` to the list of requires in config/application.rb. That doesn't work in Rails 5 as the structure's changed, and I can't see where it should go.

For reference, if I don't add anything and just leave the gem, XML params get interpreted as a lump of text. If I do try to add in the parser, I get `cannot load such file` errors. Is there something I'm missing here?

**Comment by rafaelfranca** [comment]
It is enabled by default. When you include the gem it is already enabled.

 Can you please provide a sample application that reproduces the error?

**Comment by danwhitston** [comment]
Thanks for the response. I've been poking away further, and isolated the cause as not setting the post header to XML using `headers: { 'CONTENT_TYPE' => 'application/xml' }` in my spec files. My apologies for the confusion - I'd assumed this would happen automatically, but it makes sense that it doesn't.
