### ISSUE TITLE
REXML::ParseException - #<RuntimeError: attempted adding second root element to document

### ISSUE THREAD

**Issue by aliammaar** [rails/actionpack-xml_parser#19]
REXML::ParseException - #<RuntimeError: attempted adding second root element to document>
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/document.rb:96:in `add'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/element.rb:880:in `add'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/child.rb:22:in `initialize'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/parent.rb:14:in `initialize'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/element.rb:60:in `initialize'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/element.rb:878:in `new'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/element.rb:878:in `add'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/element.rb:298:in `add_element'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/document.rb:103:in `add_element'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:34:in `parse'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/document.rb:288:in `build'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rexml/document.rb:45:in `initialize'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini/rexml.rb:29:in `new'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini/rexml.rb:29:in `parse'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini.rb:101:in `parse'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/hash/conversions.rb:153:in `initialize'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/hash/conversions.rb:130:in `new'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/hash/conversions.rb:130:in `from_xml'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-xml_parser-2.0.1/lib/action_pack/xml_parser.rb:15:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/parameters.rb:112:in `parse_formatted_parameters'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/request.rb:381:in `block in POST'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/request.rb:59:in `fetch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/request.rb:59:in `fetch_header'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/request.rb:380:in `POST'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/parameters.rb:55:in `parameters'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:23:in `process_action'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:559:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/better_errors-2.5.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/better_errors-2.5.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/better_errors-2.5.1/lib/better_errors/middleware.rb:57:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:605:in `process_client'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:700:in `worker_loop'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:144:in `start'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-handlers-0.7.3/lib/rack/handler/unicorn.rb:19:in `run'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/server.rb:297:in `start'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:53:in `start'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
/home/developer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
...
attempted adding second root element to document
Line: 3
Position: 76
Last 80 unconsumed characters:
:

**Comment by aliammaar** [comment]
its working if wrap the params like this
<client_request>
<rootelem>resource_identifier</rootelem>
<resource_id>105</resource_id>
<another_param>19000000007</another_param>
<yet_another_param>LGS</yet_another_param>
</clilent_request>

**Comment by aliammaar** [comment]
but the issue is client app unable to wrap the params in <client_request> </client_request>.
any help or lead would be much appreciated.
thanks

**Comment by rafaelfranca** [comment]
Thank you for the issue. There is nothing we can do here. If the client send invalid request, we will not be able to parse.
