### ISSUE TITLE
Can't install on Rails 4.1

### ISSUE THREAD

**Issue by mrsimo** [rails/actionpack-xml_parser#6]
This is what I get from bundler when trying to install on Rails 4.1.9:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    activeresource (>= 0) ruby depends on
      activesupport (~> 4.0) ruby

    actionpack-xml_parser (>= 1.0.1) ruby depends on
      actionpack (>= 4.0.0.rc1) ruby depends on
        activesupport (4.0.0.rc1)
```

I forked this repo and used that instead of the current one in rubygems (1.0.1) and it just works. The one in rubygems mentions `actionpack >= 4.0.0.rc1`, which doesn't seem to match [what's currently in this repository](https://github.com/rails/actionpack-xml_parser/blob/master/actionpack-xml_parser.gemspec#L20).

I think it just need to be pushed again to rubygems.

**Comment by thenadz** [comment]
+1

**Comment by robin850** [comment]
It looks like you have to run `rm Gemfile.lock && bundle install` ; I'm able to install this gem inside a 4.2.3 application. Thanks for reporting anyway!
