### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by swistak35** [rails/actionpack-xml_parser#7]
Could we please bump the version? There's quite important bugfixing commit: https://github.com/rails/actionpack-xml_parser/commit/2192ac09f212fe079d4302baafa84fe9f7a84ad8

However it's not published on rubygems, so I pulled to my project old version with the bug.

This bug caused that after enabling this gem, `request.raw_post` and `request.env["RAW_POST_DATA"]` was always empty.

**Comment by sikachu** [comment]
Definitely! Thanks for pinging us.

I'll get this out today.

**Comment by swistak35** [comment]
Thank you very much! :+1:

**Comment by sikachu** [comment]
I'm waiting for rails/rails#19802 to merge before I do the release, as the test is currently failing against Rails master.

**Comment by sikachu** [comment]
Gem pushed. Enjoy!

https://rubygems.org/gems/actionpack-xml_parser/versions/1.0.2
